### ISSUE TITLE
Add filters

### ISSUE THREAD

**Issue by prolic** [TomasVotruba/friendsofphp.org#116] opened 2019-02-07 18:37 UTC
I would like to be able to filter specific meetups that I am / I am not interested.
F.e. there are many many wordpress meetups, but when I am not interested in wordpress at all, then looking for a meetup might take more time than expected.

**Comment by TomasVotruba** [comment] 2019-02-07 19:13
How would you implement it?

**Comment by prolic** [comment] 2019-02-07 20:57
I didn't look into the code base at all, so this may not be useful: Either by filtering by meetup name (I want to look for meetups only containing / not containing the string "wordpress") or each meetup can have different tags, so you can filter by tags.
If you think it's not worth it, feel free to just close this issue, it's only a wish, not a requirement from my side :)

**Comment by TomasVotruba** [comment] 2019-02-07 21:01
> If you think it's not worth it, feel free to just close this issue, it's only a wish, not a requirement from my side :)

Oh no, I like it :+1: 

> I didn't look into the code base at all, so this may not be useful: Either by filtering by meetup name (I want to look for meetups only containing / not containing the string "wordpress") or each meetup can have different tags, so you can filter by tags.

I can add tags to meetups based on name or group name.

The website is static - Javascript - and my Javascript skills are like -500 :/

That's why I ask how would such filter look like implemented in current website.

**Comment by prolic** [comment] 2019-02-07 21:14
I don't want to lie or pretend I know something, so I just say this: sorry, no idea :-)
Quickly checked html sources, I see you use jQuery, so maybe http://api.jquery.com/filter/ helps or doesn't help. Maybe also https://api.jquerymobile.com/filterable/ helps, or maybe those hints are totally annoying because I don't know the source code at all and it's totally stupid that I suggest those :)

**Comment by TomasVotruba** [comment] 2019-02-07 21:55
Well, if you make an implementation that works, feel free to send PR. I'd love some filtering too :+1:

**Comment by prolic** [comment] 2019-02-08 08:17
Sorry I won't have the time now.

**Comment by TomasVotruba** [comment] 2019-02-08 11:06
No troubles. Send when ready.

Also duplicate of #114

**Closed** 2019-04-07 10:54 UTC
